//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psmportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_evaluator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_evaluator()
        {
            this.tb_evaluation = new HashSet<tb_evaluation>();
            this.tb_proposal = new HashSet<tb_proposal>();
            this.tb_proposal1 = new HashSet<tb_proposal>();
        }
    
        public string EvaluatorIC { get; set; }
        public string OwnedStudentIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_evaluation> tb_evaluation { get; set; }
        public virtual tb_lecturer tb_lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_proposal> tb_proposal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_proposal> tb_proposal1 { get; set; }
    }
}
