//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psmportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_request
    {
        public int RequestID { get; set; }
        public string StudentIC { get; set; }
        public string SupervisorIC { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
    
        public virtual tb_lecturer tb_lecturer { get; set; }
        public virtual tb_student tb_student { get; set; }
    }
}
